{
 "title": "Road Segment 1 Visualizations",
 "time": { "from": "2024-03-05T14:34:00.000Z", "to": "2024-03-05T14:34:10.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Reports to the Database",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timeperiod \r\nFROM roadtime \r\nORDER BY timeperiod DESC  \r\nLIMIT 3"
    }
   ]
  },
  {
   "title": "Throughput (cars/s) over time for Road Segment #1",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT throughput, timeperiod as \"time\"\r\nFROM during WHERE roadsegmentid=1"
    }
   ]
  },
  {
   "title": "Speed (km/s) on Road Segment #1 over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT avgspeed as \"average speed\", postedspeed as \"posted speed\", timeperiod as \"TIME\"\r\nFROM during \r\nWHERE roadsegmentid=1"
    }
   ]
  },
  {
   "title": "Number of Cars over time for Road Segment #1",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT numcars as \"number of cars\", timeperiod as \"time\"  \r\nFROM during WHERE roadsegmentid=1"
    }
   ]
  }
 ]
}