/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CooperativeControlMessage"
 * 	found in "CooperativeControlMsg-v1-ph.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_CooperativeControlMessage_H_
#define	_CooperativeControlMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CooperativeControlMessage */
typedef NULL_t	 CooperativeControlMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CooperativeControlMessage;
asn_struct_free_f CooperativeControlMessage_free;
asn_struct_print_f CooperativeControlMessage_print;
asn_constr_check_f CooperativeControlMessage_constraint;
ber_type_decoder_f CooperativeControlMessage_decode_ber;
der_type_encoder_f CooperativeControlMessage_encode_der;
xer_type_decoder_f CooperativeControlMessage_decode_xer;
xer_type_encoder_f CooperativeControlMessage_encode_xer;
oer_type_decoder_f CooperativeControlMessage_decode_oer;
oer_type_encoder_f CooperativeControlMessage_encode_oer;
per_type_decoder_f CooperativeControlMessage_decode_uper;
per_type_encoder_f CooperativeControlMessage_encode_uper;
per_type_decoder_f CooperativeControlMessage_decode_aper;
per_type_encoder_f CooperativeControlMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CooperativeControlMessage_H_ */
#include "asn_internal.h"
