/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TollUsageAckMessage"
 * 	found in "TollUsageAckMsg-v0.10-ph.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_TollUsageAckMessage_H_
#define	_TollUsageAckMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TollUsageAckMessage */
typedef NULL_t	 TollUsageAckMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TollUsageAckMessage;
asn_struct_free_f TollUsageAckMessage_free;
asn_struct_print_f TollUsageAckMessage_print;
asn_constr_check_f TollUsageAckMessage_constraint;
ber_type_decoder_f TollUsageAckMessage_decode_ber;
der_type_encoder_f TollUsageAckMessage_encode_der;
xer_type_decoder_f TollUsageAckMessage_decode_xer;
xer_type_encoder_f TollUsageAckMessage_encode_xer;
oer_type_decoder_f TollUsageAckMessage_decode_oer;
oer_type_encoder_f TollUsageAckMessage_encode_oer;
per_type_decoder_f TollUsageAckMessage_decode_uper;
per_type_encoder_f TollUsageAckMessage_encode_uper;
per_type_decoder_f TollUsageAckMessage_decode_aper;
per_type_encoder_f TollUsageAckMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TollUsageAckMessage_H_ */
#include "asn_internal.h"
