/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TollUsageMessage"
 * 	found in "TollUsageMsg-v0.10-ph.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_TollUsageMessage_H_
#define	_TollUsageMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TollUsageMessage */
typedef NULL_t	 TollUsageMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TollUsageMessage;
asn_struct_free_f TollUsageMessage_free;
asn_struct_print_f TollUsageMessage_print;
asn_constr_check_f TollUsageMessage_constraint;
ber_type_decoder_f TollUsageMessage_decode_ber;
der_type_encoder_f TollUsageMessage_encode_der;
xer_type_decoder_f TollUsageMessage_decode_xer;
xer_type_encoder_f TollUsageMessage_encode_xer;
oer_type_decoder_f TollUsageMessage_decode_oer;
oer_type_encoder_f TollUsageMessage_encode_oer;
per_type_decoder_f TollUsageMessage_decode_uper;
per_type_encoder_f TollUsageMessage_encode_uper;
per_type_decoder_f TollUsageMessage_decode_aper;
per_type_encoder_f TollUsageMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TollUsageMessage_H_ */
#include "asn_internal.h"
