/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TollAdvertisementMessage"
 * 	found in "TollAdvertisementMsg-v0.10-ph.asn"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -fincludes-quoted -no-gen-JER`
 */

#ifndef	_TollAdvertisementMessage_H_
#define	_TollAdvertisementMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TollAdvertisementMessage */
typedef NULL_t	 TollAdvertisementMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TollAdvertisementMessage;
asn_struct_free_f TollAdvertisementMessage_free;
asn_struct_print_f TollAdvertisementMessage_print;
asn_constr_check_f TollAdvertisementMessage_constraint;
ber_type_decoder_f TollAdvertisementMessage_decode_ber;
der_type_encoder_f TollAdvertisementMessage_encode_der;
xer_type_decoder_f TollAdvertisementMessage_decode_xer;
xer_type_encoder_f TollAdvertisementMessage_encode_xer;
oer_type_decoder_f TollAdvertisementMessage_decode_oer;
oer_type_encoder_f TollAdvertisementMessage_encode_oer;
per_type_decoder_f TollAdvertisementMessage_decode_uper;
per_type_encoder_f TollAdvertisementMessage_encode_uper;
per_type_decoder_f TollAdvertisementMessage_decode_aper;
per_type_encoder_f TollAdvertisementMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TollAdvertisementMessage_H_ */
#include "asn_internal.h"
